### ISSUE TITLE
Project fails to build on VS 2015

### ISSUE THREAD

**Issue by TritonJak** [catid/cm256#2]
Dear Catid,

Recently I've tried to build this project on the latest version of VS 2015. I've noted that in your readme, you've stated that this project only works on the 2013 edition. 
I was just wondering if this still works in general since the tests that I tried running in main (in the unit tests folder, disabling the performance tests leaving only the example file usage and the check memswap) failed. 

Note that I have not changed anything at all in the source apart from disabling the compilation of the performance tests. 

This is the result of the debug output in VS

```
'matrix_test.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot find or open the PDB file.
'matrix_test.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Cannot find or open the PDB file.
'matrix_test.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Cannot find or open the PDB file.
'matrix_test.exe' (Win32): Loaded 'C:\Windows\SysWOW64\apphelp.dll'. Cannot find or open the PDB file.
The program '[9996] matrix_test.exe' has exited with code 3 (0x3).
```

Apologies if this is the wrong place to ask this, I'm new to programming in VS.

Sincerely,
TritonJak

**Comment by catid** [comment]
I haven't tried building on 2015 yet.  Not sure what will happen!

Will give it a shot soon.

**Comment by TritonJak** [comment]
Thanks! It's probably something simple or stupid that I missed >__<
