### ISSUE TITLE
compile error in linux

### ISSUE THREAD

**Issue by zerojiu** [catid/cm256#4]
hi, i am using this library for my application which run on linux.
Does this library support linux?  The follow is error ScreenShot:

![image](https://user-images.githubusercontent.com/7017760/47068762-ca05d880-d21f-11e8-8198-3321dce0c84d.png)

错误 in screenshot means error

thx very much.

**Comment by catid** [comment]
Try building with -march=native

**Comment by zerojiu** [comment]
problem solved. I really appreciate it.
